// src/app/layout.tsx

import type { Metadata } from "next";
import "./globals.css";
import OidcProviderWrapper from "@/components/OidcProviderWrapper";
import ClientLayoutWrapper from "@/components/ClientLayoutWrapper";
import { JetBrains_Mono } from "next/font/google";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Spark Link",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className={`${jetBrainsMono.className} h-full flex flex-col`}>
        <OidcProviderWrapper>
          <ClientLayoutWrapper>{children}</ClientLayoutWrapper>
        </OidcProviderWrapper>
      </body>
    </html>
  );
}
