// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import OidcProviderWrapper from "@/components/OidcProviderWrapper";

export const metadata: Metadata = {
  title: "Spark Link",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <OidcProviderWrapper>
          {children}
        </OidcProviderWrapper>
      </body>
    </html>
  );
}
